import mongoose, { Document, Schema, Model } from 'mongoose';

interface IBalanceUser extends Document {
  id: Number,
  main: {
    usdt: Number,
    mine: Number,
    plex: Number,
    mpx: Number,
    xfi: Number,
    artery: Number,
    bip: Number,
    hub: Number,
    monsterhub: Number,
    bnb: Number,
    usdtbsc: Number,
    bipkakaxa: Number,
    cashbsc: Number,
    minterBazercoin: Number,
    ruble: Number,
    cashback: Number,
    del: Number,
    ddao: Number,
    delkakaxa: Number,
    converter: Number,
    pro: Number,
    dar: Number,
    sbt: Number,
    reboot: Number,
    makarovsky: Number,
    btt: Number,
    dixwell: Number,
    avt: Number,
    kharat: Number,
    byacademy: Number,
    itcoin: Number,
    patrick: Number,
    messege: Number,
    rrunion: Number,
    vegvisir: Number,
    fbworld: Number,
    dcschool: Number,
    comcoin: Number,
    mintcandy: Number,
    sirius: Number,
    cgttoken: Number,
    genesis: Number,
    taxicoin: Number,
    prosmm: Number,
    sharafi: Number,
    safecoin: Number,
    dtradecoin: Number,
    izicoin: Number,
    gzacademy: Number,
    workout: Number,
    zaruba: Number,
    magnetar: Number,
    candypop: Number,
    randomx: Number,
    ekology: Number,
    emelyanov: Number,
    belymag: Number,
    doorhan: Number,
    lakshmi: Number,
    ryabinin: Number,
    related: Number,
    monopoly: Number,
    baroncoin: Number,
    nashidela: Number,
    irmacoin: Number,
    maritime: Number,
    business: Number,
    randice: Number,
    alleluia: Number,
    hosanna: Number,
    cbgrewards: Number,
    novoselka: Number,
    monkeyclub: Number,
    grandpay: Number,
    magnate: Number,
    crypton: Number,
    iloveyou: Number,
    bazercoin: Number,
    bazerusd: Number,

  },
  hold:{
    usdt: Number,
    mine: Number,
    plex: Number,
    mpx: Number,
    xfi: Number,
    bip: Number,
    hub: Number,
    monsterhub: Number,
    bnb: Number,
    usdtbsc: Number,
    bipkakaxa: Number,
    cashbsc: Number,
    minterBazercoin: Number,
    ruble: Number,
    del: Number,
    cashback: Number,
    artery: Number,
    ddao: Number,
    delkakaxa: Number,
    converter: Number,
    pro: Number,
    dar: Number,
    sbt: Number,
    reboot: Number,
    makarovsky: Number,
    btt: Number,
    dixwell: Number,
    avt: Number,
    kharat: Number,
    byacademy: Number,
    itcoin: Number,
    patrick: Number,
    messege: Number,
    rrunion: Number,
    vegvisir: Number,
    fbworld: Number,
    dcschool: Number,
    comcoin: Number,
    mintcandy: Number,
    sirius: Number,
    cgttoken: Number,
    genesis: Number,
    taxicoin: Number,
    prosmm: Number,
    sharafi: Number,
    safecoin: Number,
    dtradecoin: Number,
    izicoin: Number,
    gzacademy: Number,
    workout: Number,
    zaruba: Number,
    magnetar: Number,
    candypop: Number,
    randomx: Number,
    ekology: Number,
    emelyanov: Number,
    belymag: Number,
    doorhan: Number,
    lakshmi: Number,
    ryabinin: Number,
    related: Number,
    monopoly: Number,
    baroncoin: Number,
    nashidela: Number,
    irmacoin: Number,
    maritime: Number,
    business: Number,
    randice: Number,
    alleluia: Number,
    hosanna: Number,
    cbgrewards: Number,
    novoselka: Number,
    monkeyclub: Number,
    grandpay: Number,
    magnate: Number,
    crypton: Number,
    iloveyou: Number,
    bazercoin: Number,
    bazerusd: Number,
  }
}

const BalanceUserSchema: Schema<IBalanceUser> = new Schema({
  id: { type: Number, required: true },
  main: {
    usdt: { type: Number, required: true },
    mine: { type: Number, required: true },
    plex: { type: Number, required: true },
    mpx: { type: Number, required: true },
    xfi: { type: Number, required: true },
    artery: { type: Number, required: true },
    bip: { type: Number, required: true },
    hub: { type: Number, required: true },
    monsterhub: { type: Number, required: true },
    bnb: { type: Number, required: true },
    usdtbsc: { type: Number, required: true },
    bipkakaxa: { type: Number, required: true },
    cashbsc: { type: Number, required: true },
    minterBazercoin: { type: Number, required: true },
    ruble: { type: Number, required: true },
    cashback: { type: Number, required: true },
    del: { type: Number, required: true },
    ddao: { type: Number, required: true },
    delkakaxa: { type: Number, required: true },
    converter: { type: Number, required: true },
    pro: { type: Number, required: true },
    dar: { type: Number, required: true },
    sbt: { type: Number, required: true },
    reboot: { type: Number, required: true },
    makarovsky: { type: Number, required: true },
    btt: { type: Number, required: true },
    dixwell: { type: Number, required: true },
    avt: { type: Number, required: true },
    kharat: { type: Number, required: true },
    byacademy: { type: Number, required: true },
    itcoin: { type: Number, required: true },
    patrick: { type: Number, required: true },
    messege: { type: Number, required: true },
    rrunion: { type: Number, required: true },
    vegvisir: { type: Number, required: true },
    fbworld: { type: Number, required: true },
    dcschool: { type: Number, required: true },
    comcoin: { type: Number, required: true },
    mintcandy: { type: Number, required: true },
    sirius: { type: Number, required: true },
    cgttoken: { type: Number, required: true },
    genesis: { type: Number, required: true },
    taxicoin: { type: Number, required: true },
    prosmm: { type: Number, required: true },
    sharafi: { type: Number, required: true },
    safecoin: { type: Number, required: true },
    dtradecoin: { type: Number, required: true },
    izicoin: { type: Number, required: true },
    gzacademy: { type: Number, required: true },
    workout: { type: Number, required: true },
    zaruba: { type: Number, required: true },
    magnetar: { type: Number, required: true },
    candypop: { type: Number, required: true },
    randomx: { type: Number, required: true },
    ekology: { type: Number, required: true },
    emelyanov: { type: Number, required: true },
    belymag: { type: Number, required: true },
    doorhan: { type: Number, required: true },
    lakshmi: { type: Number, required: true },
    ryabinin: { type: Number, required: true },
    related: { type: Number, required: true },
    monopoly: { type: Number, required: true },
    baroncoin: { type: Number, required: true },
    nashidela: { type: Number, required: true },
    irmacoin: { type: Number, required: true },
    maritime: { type: Number, required: true },
    business: { type: Number, required: true },
    randice: { type: Number, required: true },
    alleluia: { type: Number, required: true },
    hosanna: { type: Number, required: true },
    cbgrewards: { type: Number, required: true },
    novoselka: { type: Number, required: true },
    monkeyclub: { type: Number, required: true },
    grandpay: { type: Number, required: true },
    magnate: { type: Number, required: true },
    crypton: { type: Number, required: true },
    iloveyou: { type: Number, required: true },
    bazercoin: { type: Number, required: true },
    bazerusd: { type: Number, required: true },
  },
  hold: {
    usdt: { type: Number, required: true },
    mine: { type: Number, required: true },
    plex: { type: Number, required: true },
    mpx: { type: Number, required: true },
    xfi: { type: Number, required: true },
    artery: { type: Number, required: true },
    bip: { type: Number, required: true },
    hub: { type: Number, required: true },
    monsterhub: { type: Number, required: true },
    bnb: { type: Number, required: true },
    usdtbsc: { type: Number, required: true },
    bipkakaxa: { type: Number, required: true },
    cashbsc: { type: Number, required: true },
    minterBazercoin: { type: Number, required: true },
    ruble: { type: Number, required: true },
    cashback: { type: Number, required: true },
    del: { type: Number, required: true },
    ddao: { type: Number, required: true },
    delkakaxa: { type: Number, required: true },
    converter: { type: Number, required: true },
    pro: { type: Number, required: true },
    dar: { type: Number, required: true },
    sbt: { type: Number, required: true },
    reboot: { type: Number, required: true },
    makarovsky: { type: Number, required: true },
    btt: { type: Number, required: true },
    dixwell: { type: Number, required: true },
    avt: { type: Number, required: true },
    kharat: { type: Number, required: true },
    byacademy: { type: Number, required: true },
    itcoin: { type: Number, required: true },
    patrick: { type: Number, required: true },
    messege: { type: Number, required: true },
    rrunion: { type: Number, required: true },
    vegvisir: { type: Number, required: true },
    fbworld: { type: Number, required: true },
    dcschool: { type: Number, required: true },
    comcoin: { type: Number, required: true },
    mintcandy: { type: Number, required: true },
    sirius: { type: Number, required: true },
    cgttoken: { type: Number, required: true },
    genesis: { type: Number, required: true },
    taxicoin: { type: Number, required: true },
    prosmm: { type: Number, required: true },
    sharafi: { type: Number, required: true },
    safecoin: { type: Number, required: true },
    dtradecoin: { type: Number, required: true },
    izicoin: { type: Number, required: true },
    gzacademy: { type: Number, required: true },
    workout: { type: Number, required: true },
    zaruba: { type: Number, required: true },
    magnetar: { type: Number, required: true },
    candypop: { type: Number, required: true },
    randomx: { type: Number, required: true },
    ekology: { type: Number, required: true },
    emelyanov: { type: Number, required: true },
    belymag: { type: Number, required: true },
    doorhan: { type: Number, required: true },
    lakshmi: { type: Number, required: true },
    ryabinin: { type: Number, required: true },
    related: { type: Number, required: true },
    monopoly: { type: Number, required: true },
    baroncoin: { type: Number, required: true },
    nashidela: { type: Number, required: true },
    irmacoin: { type: Number, required: true },
    maritime: { type: Number, required: true },
    business: { type: Number, required: true },
    randice: { type: Number, required: true },
    alleluia: { type: Number, required: true },
    hosanna: { type: Number, required: true },
    cbgrewards: { type: Number, required: true },
    novoselka: { type: Number, required: true },
    monkeyclub: { type: Number, required: true },
    grandpay: { type: Number, required: true },
    magnate: { type: Number, required: true },
    crypton: { type: Number, required: true },
    iloveyou: { type: Number, required: true },
    bazercoin: { type: Number, required: true },
    bazerusd: { type: Number, required: true },
  }
});

const BalanceUserModel: Model<IBalanceUser> = mongoose.model<IBalanceUser>('BalanceUsers', BalanceUserSchema);

export default BalanceUserModel;
